version: '3.4'

services:
  projeto.identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Homolog
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro