// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.Identity.Data.Context;

#nullable disable

namespace Projeto.Identity.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("SistemaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SistemaId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.HasKey("Id", "SistemaId");

                    b.HasIndex("SistemaId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("IDX_SistemaId_NomePerfil");

                    b.ToTable("Perfil", (string)null);
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.PerfilPermissao", b =>
                {
                    b.Property<Guid>("IdPerfilPermissao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdPerfilPermissao");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PerfilId");

                    b.Property<Guid>("PermissaoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PermissaoId");

                    b.Property<Guid>("SistemaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SistemaId");

                    b.HasKey("IdPerfilPermissao");

                    b.HasIndex("PermissaoId");

                    b.HasIndex("PerfilId", "SistemaId");

                    b.ToTable("PerfilxPermissao", (string)null);
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Descricao");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("Permissao", (string)null);
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Sistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Versao");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Sistema", (string)null);
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCriacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Senha");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.UsuarioPerfilSistema", b =>
                {
                    b.Property<Guid>("IdUsuarioPerfilSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdUsuarioPerfilSistema");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PerfilId");

                    b.Property<Guid>("SistemaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SistemaId");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuarioId");

                    b.HasKey("IdUsuarioPerfilSistema");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("PerfilId", "SistemaId");

                    b.HasIndex("SistemaId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("IDX_SistemaId_UsuarioId");

                    b.ToTable("UsuarioxPerfilxSistema", (string)null);
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Perfil", b =>
                {
                    b.HasOne("Projeto.Identity.Domain.Entities.Sistema", "Sistema")
                        .WithMany("Perfils")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.PerfilPermissao", b =>
                {
                    b.HasOne("Projeto.Identity.Domain.Entities.Permissao", "Permissao")
                        .WithMany("PerfilxPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto.Identity.Domain.Entities.Perfil", "Perfil")
                        .WithMany("PerfilxPermissoes")
                        .HasForeignKey("PerfilId", "SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.UsuarioPerfilSistema", b =>
                {
                    b.HasOne("Projeto.Identity.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioxPerfilxSistemas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto.Identity.Domain.Entities.Perfil", "Perfil")
                        .WithMany("UsuarioxPerfilxSistemas")
                        .HasForeignKey("PerfilId", "SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("PerfilxPermissoes");

                    b.Navigation("UsuarioxPerfilxSistemas");
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Permissao", b =>
                {
                    b.Navigation("PerfilxPermissoes");
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Sistema", b =>
                {
                    b.Navigation("Perfils");
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioxPerfilxSistemas");
                });
#pragma warning restore 612, 618
        }
    }
}
