// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.Identity.Data.Context;

#nullable disable

namespace Projeto.Identity.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("SistemaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SistemaId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.HasKey("Id", "SistemaId");

                    b.HasIndex("SistemaId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("IDX_SistemaId_NomePerfil");

                    b.ToTable("Perfil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3"),
                            Nome = "Administrador"
                        });
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.PerfilPermissao", b =>
                {
                    b.Property<Guid>("IdPerfilPermissao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdPerfilPermissao");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PerfilId");

                    b.Property<Guid>("PermissaoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PermissaoId");

                    b.Property<Guid>("SistemaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SistemaId");

                    b.HasKey("IdPerfilPermissao");

                    b.HasIndex("PermissaoId");

                    b.HasIndex("PerfilId", "SistemaId");

                    b.HasIndex("SistemaId", "PerfilId", "PermissaoId")
                        .IsUnique()
                        .HasDatabaseName("IDX_SistemaId_PerfilId_PermissaoId");

                    b.ToTable("PerfilxPermissao", (string)null);

                    b.HasData(
                        new
                        {
                            IdPerfilPermissao = new Guid("1e8ace90-b253-44bb-ac04-cdf769f9a13f"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("6379def6-d59a-4177-8449-509bd590beca"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("7b8f482d-98e5-4fc5-be55-0645e22ea8e0"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("13c017c3-b8a2-4534-bf6d-253c11216ad5"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("59af7ee6-24c6-45a9-9a00-611a77d03584"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("971b0c25-b4d2-4f6a-b053-0bd06aa7cb10"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("4a089131-0f56-42bd-b1a1-879c84eac049"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("86991fc1-2ef8-4130-8fd4-8306c561b88f"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("281de7cc-5522-45ea-a5f2-17ab372e20b6"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("341cfb71-b67c-40da-ac16-cbc2e33ef1df"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("cf442999-2f9a-4e64-8e71-163897554a39"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("3352ea24-409a-4d15-99fe-f2c813162537"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("283238fa-f134-44bb-a825-96db518a33ab"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("f8609b69-6362-485d-b61c-a6e93e8ad7e1"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("2dcc2913-182e-4dc4-8c14-7163865aa117"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("81e5c09e-3ec2-465c-94b8-72ce5a810f68"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("a8fb92fc-29ba-499c-b93a-3645583575e8"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("3e6126c4-d927-4db6-a65f-d123a9baf0f9"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("fb94adc1-767f-4f11-a8a9-a90084a153d0"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("7242b1bd-1bea-4a8d-ab6b-e54e024c919e"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("9af4791d-b572-4cd4-aeba-cda85ae55154"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("09f6869b-c36a-44d2-99df-c6b47556fb8b"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("92b99cc0-9d43-46d0-a079-8fe3358979f7"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("e732be1c-dede-4283-884a-08e5bd39e671"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("04fd5046-33ac-46ed-946e-118872f2c3ee"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("a9fe837b-1c01-4a0d-9452-e0f7ddca0d43"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("5fc5e2c7-50a0-45a4-ab30-3af38599a20d"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("8d9afc47-c1ea-4169-a1cc-ca9764f995b2"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("77cfc277-b1ac-49c1-aa58-2f351cd70c0d"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("aba4f16b-28d6-41dc-ba69-e047ca6789ef"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("c2920dfd-6bcd-4c07-b52a-7126ef15b126"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("295e726d-a499-496a-bbb0-052d5dd2342a"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("4fd68888-46a3-4356-ad2b-866104fcde07"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("7aefa33c-3f72-479b-a2ce-bdd67796772c"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("28122c68-fe1e-423d-b197-93d8dcc07894"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("722abbe6-0d22-4403-8006-3b128e5197dc"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("e85b112c-ba6b-4659-af80-acb12e3fc4c1"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("167324b1-e5aa-41ce-b8a8-4d9c33e9839d"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("208488a9-d262-48f3-a31f-ec68e12148d8"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("d96fc8a0-a114-4a14-81c2-eba4950aa25c"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("33e3468a-d90b-44ec-9fc7-fbd4fdd297fb"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("ad9d76a4-9970-440f-a948-130b650092ac"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("dd5675da-3c41-4a34-b008-a9192012beb8"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("ace0f930-6c44-4fef-aa8a-5a92a1fc8402"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("039439cc-98e7-41dd-bafa-cb5482b56685"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("cf770f57-0819-4002-88ad-3f58aa9b905a"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("25befaa8-0fe1-4523-b109-753cd0f51a71"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("713c70a4-3f9a-4d17-a086-e6d6278281fa"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("693fb084-5389-4d76-b864-74b50448e52c"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("c06ece55-d006-457c-bc8b-f7a6cf89b157"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("89c77bed-8aac-454e-8d75-3aee0e25880d"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("648717f2-97d3-42b2-8242-a2dba4d43d4d"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("6b98ed13-1d92-4124-b5b9-a27662de861f"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("b6168204-00d8-460c-8185-866c2fd993a4"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("585fc39f-3c00-4c9d-a94d-472046a28b03"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("42610841-0f94-4130-bd22-5180344e2a14"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("e1f2c33d-d5c2-4383-9c1c-bf3d633af711"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("6fecb76a-e5fe-4c04-8db5-71fbc5c87d9e"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        },
                        new
                        {
                            IdPerfilPermissao = new Guid("8cf6fb22-4d86-4cf8-aac3-903d3045b2f7"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            PermissaoId = new Guid("e7064c92-3cac-4dbc-811d-f5bc80a2acef"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3")
                        });
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("ChaveAutorizacao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ChaveAutorizacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Descricao");

                    b.HasKey("Id");

                    b.HasIndex("ChaveAutorizacao")
                        .IsUnique();

                    b.ToTable("Permissao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6379def6-d59a-4177-8449-509bd590beca"),
                            ChaveAutorizacao = "CadastrarPerfil",
                            Descricao = "Cadastrar Perfil"
                        },
                        new
                        {
                            Id = new Guid("13c017c3-b8a2-4534-bf6d-253c11216ad5"),
                            ChaveAutorizacao = "EditarPerfil",
                            Descricao = "Editar Perfil"
                        },
                        new
                        {
                            Id = new Guid("971b0c25-b4d2-4f6a-b053-0bd06aa7cb10"),
                            ChaveAutorizacao = "ExcluirPerfil",
                            Descricao = "Excluir Perfil"
                        },
                        new
                        {
                            Id = new Guid("86991fc1-2ef8-4130-8fd4-8306c561b88f"),
                            ChaveAutorizacao = "ListarPerfil",
                            Descricao = "Listar Perfil"
                        },
                        new
                        {
                            Id = new Guid("341cfb71-b67c-40da-ac16-cbc2e33ef1df"),
                            ChaveAutorizacao = "ListarFiltroPerfil",
                            Descricao = "Listar Filtro Perfil"
                        },
                        new
                        {
                            Id = new Guid("3352ea24-409a-4d15-99fe-f2c813162537"),
                            ChaveAutorizacao = "ObterPorIdPerfil",
                            Descricao = "Obter Por Id Perfil"
                        },
                        new
                        {
                            Id = new Guid("f8609b69-6362-485d-b61c-a6e93e8ad7e1"),
                            ChaveAutorizacao = "CadastrarPerfilPermissao",
                            Descricao = "Cadastrar Perfil Permissao"
                        },
                        new
                        {
                            Id = new Guid("81e5c09e-3ec2-465c-94b8-72ce5a810f68"),
                            ChaveAutorizacao = "ExcluirPerfilPermissao",
                            Descricao = "Excluir Perfil Permissao"
                        },
                        new
                        {
                            Id = new Guid("3e6126c4-d927-4db6-a65f-d123a9baf0f9"),
                            ChaveAutorizacao = "ListarPerfilPermissao",
                            Descricao = "Listar Perfil Permissao"
                        },
                        new
                        {
                            Id = new Guid("7242b1bd-1bea-4a8d-ab6b-e54e024c919e"),
                            ChaveAutorizacao = "CadastrarPermissao",
                            Descricao = "Cadastrar Permissao"
                        },
                        new
                        {
                            Id = new Guid("09f6869b-c36a-44d2-99df-c6b47556fb8b"),
                            ChaveAutorizacao = "EditarPermissao",
                            Descricao = "Editar Permissao"
                        },
                        new
                        {
                            Id = new Guid("e732be1c-dede-4283-884a-08e5bd39e671"),
                            ChaveAutorizacao = "ExcluirPermissao",
                            Descricao = "Excluir Permissao"
                        },
                        new
                        {
                            Id = new Guid("a9fe837b-1c01-4a0d-9452-e0f7ddca0d43"),
                            ChaveAutorizacao = "ListarPermissao",
                            Descricao = "Listar Permissao"
                        },
                        new
                        {
                            Id = new Guid("8d9afc47-c1ea-4169-a1cc-ca9764f995b2"),
                            ChaveAutorizacao = "ListarFiltroPermissao",
                            Descricao = "Listar Filtro Permissao"
                        },
                        new
                        {
                            Id = new Guid("aba4f16b-28d6-41dc-ba69-e047ca6789ef"),
                            ChaveAutorizacao = "ObterPorIdPermissao",
                            Descricao = "Obter Por Id Permissao"
                        },
                        new
                        {
                            Id = new Guid("295e726d-a499-496a-bbb0-052d5dd2342a"),
                            ChaveAutorizacao = "CadastrarSistema",
                            Descricao = "Cadastrar Sistema"
                        },
                        new
                        {
                            Id = new Guid("7aefa33c-3f72-479b-a2ce-bdd67796772c"),
                            ChaveAutorizacao = "EditarSistema",
                            Descricao = "Editar Sistema"
                        },
                        new
                        {
                            Id = new Guid("722abbe6-0d22-4403-8006-3b128e5197dc"),
                            ChaveAutorizacao = "ExcluirSistema",
                            Descricao = "Excluir Sistema"
                        },
                        new
                        {
                            Id = new Guid("167324b1-e5aa-41ce-b8a8-4d9c33e9839d"),
                            ChaveAutorizacao = "ListarSistema",
                            Descricao = "Listar Sistema"
                        },
                        new
                        {
                            Id = new Guid("d96fc8a0-a114-4a14-81c2-eba4950aa25c"),
                            ChaveAutorizacao = "ListarFiltroSistema",
                            Descricao = "Listar Filtro Sistema"
                        },
                        new
                        {
                            Id = new Guid("ad9d76a4-9970-440f-a948-130b650092ac"),
                            ChaveAutorizacao = "ObterPorIdSistema",
                            Descricao = "Obter Por Id Sistema"
                        },
                        new
                        {
                            Id = new Guid("ace0f930-6c44-4fef-aa8a-5a92a1fc8402"),
                            ChaveAutorizacao = "ListarUsuarioPerfilSistema",
                            Descricao = "Listar Usuario Perfil Sistema"
                        },
                        new
                        {
                            Id = new Guid("cf770f57-0819-4002-88ad-3f58aa9b905a"),
                            ChaveAutorizacao = "ExcluirUsuarioPerfilSistema",
                            Descricao = "Excluir Usuario Perfil Sistema"
                        },
                        new
                        {
                            Id = new Guid("713c70a4-3f9a-4d17-a086-e6d6278281fa"),
                            ChaveAutorizacao = "CadastrarUsuarioPerfilSistema",
                            Descricao = "Cadastrar Usuario Perfil Sistema"
                        },
                        new
                        {
                            Id = new Guid("c06ece55-d006-457c-bc8b-f7a6cf89b157"),
                            ChaveAutorizacao = "CadastrarUsuario",
                            Descricao = "Cadastrar Usuario"
                        },
                        new
                        {
                            Id = new Guid("648717f2-97d3-42b2-8242-a2dba4d43d4d"),
                            ChaveAutorizacao = "Editar Usuario",
                            Descricao = "Editar Usuario"
                        },
                        new
                        {
                            Id = new Guid("b6168204-00d8-460c-8185-866c2fd993a4"),
                            ChaveAutorizacao = "ExcluirUsuario",
                            Descricao = "Excluir Usuario"
                        },
                        new
                        {
                            Id = new Guid("42610841-0f94-4130-bd22-5180344e2a14"),
                            ChaveAutorizacao = "ListarUsuario",
                            Descricao = "Listar Usuario"
                        },
                        new
                        {
                            Id = new Guid("6fecb76a-e5fe-4c04-8db5-71fbc5c87d9e"),
                            ChaveAutorizacao = "ListarFiltroUsuario",
                            Descricao = "Listar Filtro Usuario"
                        },
                        new
                        {
                            Id = new Guid("e7064c92-3cac-4dbc-811d-f5bc80a2acef"),
                            ChaveAutorizacao = "ObterPorIdUsuario",
                            Descricao = "Obter Por Id Usuario"
                        });
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Sistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Versao");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Sistema", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3"),
                            Nome = "Plataforma de Gerenciamento de Acesso Multissistema",
                            Versao = "Versão 1.0"
                        });
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCriacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Senha");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("91a19d9a-f4c3-4ebf-9de0-f2eaef912419"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "adminSystem33@gmail.com",
                            Nome = "Administrador",
                            Senha = "AQAAAAIAAYagAAAAEGZMezxOyRmyPezB01hbD6ZLmtKezSljyncwfdzovX7GhkZqyn4qYMc21qUO8X+0lw=="
                        });
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.UsuarioPerfilSistema", b =>
                {
                    b.Property<Guid>("IdUsuarioPerfilSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdUsuarioPerfilSistema");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PerfilId");

                    b.Property<Guid>("SistemaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SistemaId");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuarioId");

                    b.HasKey("IdUsuarioPerfilSistema");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("PerfilId", "SistemaId");

                    b.HasIndex("SistemaId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("IDX_SistemaId_UsuarioId");

                    b.ToTable("UsuarioxPerfilxSistema", (string)null);

                    b.HasData(
                        new
                        {
                            IdUsuarioPerfilSistema = new Guid("2c05440a-da63-4d52-9479-5599be9953e3"),
                            PerfilId = new Guid("e6d4582c-cce8-45c4-a633-08cae8d80aef"),
                            SistemaId = new Guid("6a88cdcc-d445-44d1-8ca3-7dd60ddc1af3"),
                            UsuarioId = new Guid("91a19d9a-f4c3-4ebf-9de0-f2eaef912419")
                        });
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Perfil", b =>
                {
                    b.HasOne("Projeto.Identity.Domain.Entities.Sistema", "Sistema")
                        .WithMany("Perfils")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.PerfilPermissao", b =>
                {
                    b.HasOne("Projeto.Identity.Domain.Entities.Permissao", "Permissao")
                        .WithMany("PerfilxPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto.Identity.Domain.Entities.Perfil", "Perfil")
                        .WithMany("PerfilxPermissoes")
                        .HasForeignKey("PerfilId", "SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.UsuarioPerfilSistema", b =>
                {
                    b.HasOne("Projeto.Identity.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioxPerfilxSistemas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto.Identity.Domain.Entities.Perfil", "Perfil")
                        .WithMany("UsuarioxPerfilxSistemas")
                        .HasForeignKey("PerfilId", "SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("PerfilxPermissoes");

                    b.Navigation("UsuarioxPerfilxSistemas");
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Permissao", b =>
                {
                    b.Navigation("PerfilxPermissoes");
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Sistema", b =>
                {
                    b.Navigation("Perfils");
                });

            modelBuilder.Entity("Projeto.Identity.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioxPerfilxSistemas");
                });
#pragma warning restore 612, 618
        }
    }
}
